name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Remote service stop
      uses: spcily/ssh-action@v1.0.0
      with:
          host: ${{ secrets.REMOTE_SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SERVER_PORT }}
          script: sudo systemctl stop my_telegram_bot.service
   - name: Copy via ssh
      uses: garygrossgarten/github-action-scp@v0.8.0
      with:
          local: .
          remote: /home/py-bot/
          host: ${{ secrets.REMOTE_SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Remote service start
      uses: spcily/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SERVER_PORT }}
          script: sudo systemctl start my_telegram_bot.service

            